### ISSUE TITLE
The problem

### ISSUE THREAD

**Issue by maritmartin** [Teamweek/teamweek#641]
Using google account to log in means that users have no password. But they need one to integrate with toggl. What to do? 

Marek:

Basecamp integration is made from our side. Then you don't need to autheticate for TW.
marektihkan [4:16 PM] I wouldn't want to see any password sent to my email inbox.
marektihkan [4:17 PM] Issue will be bigger when others want to integrate with us.
marektihkan [4:21 PM] For example, I create some nifty service, which needs to get data from TW. I follow OAuth flow and to get access to data it shows me login screen where no Google authentication link is available. So I need to provide my username and password.
marektihkan [4:22 PM] I havn't seen any OAuth provider who allows authenticate via 3rd party login.

**Comment by arcz** [comment]
We had discussion about that and evaluted dfferent solutions. It is not possible to chain OAuth logins, it must stay as is, so we have 3 solutions:

- drop Google auth, currently threre are about 9% of users which have used Google auth, however we don't know whether they are active or not

- add more support for handling this issue, for example make an information with links under the form, that they must (re)set password in order to integrate and provide support page which explains why.

- do nothing

**Comment by maritmartin** [comment]
Janika: We decided that for google authentication problem will be handled as follows -  
"add more support for handling this issue, for example make an information with links under the form, that they must (re)set password in order to integrate and provide support page which explains why."

If so, please provide a detailed plan - where what etc.

**Comment by arcz** [comment]
Can't log in or used Google sign up? [Reset your password](https://app.teamweek.com/#recover)

**Comment by maritmartin** [comment]
that's all, is it enough? when does this appear? where? 

as a users i would have tons of questions, why do i have to reset my password? should i reset google password? why? if not, why do i need tw password when i use google signin? etc ..

**Comment by arcz** [comment]
@maritmartin This text will be here under "Sign in" button. So yes, users can ask why they have to reset password, we thought that it would be good to add support page which explains that and link to it. Overall under the "Sign in" button there will be:

Can't log in or used Google sing up? Please [reset your Teamweek password](https://app.teamweek.com/#recover)
[Why I have to reset my Teamweek password?]()

(There will be link to support page with explanation)

**Comment by maritmartin** [comment]
i don't agree that we put so may stuff there, it's already overloaded. and isn't it misleading to show "error" message all the time? it would make sense if this message would appear after unsuccessful login with google. also, please provide @tiinakaarik with all the details to write a support article about that. 

![9998a7bc-b78a-11e4-8052-575e2ab3505a](https://cloud.githubusercontent.com/assets/5929570/6370379/6246e080-bcf8-11e4-846a-ab4c1f3c4c1a.png)

**Comment by maritmartin** [comment]
also, what will happen when i have logged in with my google account and start to integrate with basecamp?

**Comment by arcz** [comment]
The issue is happening only when other service tries to get data from Teamweek. In this case Teamweek is pulling data from Basecamp. @marektihkan Please correct me if I am wrong.

**Comment by marektihkan** [comment]
We have 2 different log in pages: Application sign in, what is used when user wants to see timeline (https://app.teamweek.com); Authorizing 3rd party application to access Teamweek's data (https://teamweek.com/oauth/login?response_type=code&client_id=teamweek_timeline). We could have bit different view for it because there is no remember me and login google plus option on 3rd party auhorization page.
