### ISSUE TITLE
Overbooking 

### ISSUE THREAD

**Issue by maritmartin** [Teamweek/teamweek#940]
the current version: 
![screen shot 2015-07-07 at 15 53 16](https://cloud.githubusercontent.com/assets/5929570/8546420/4d270a42-24c0-11e5-8467-120b80276b2a.png)

the new version: 
![timeline](https://cloud.githubusercontent.com/assets/5929570/8546425/55065d94-24c0-11e5-86a4-ed99e313fc8c.png)

**Comment by miscer** [comment]
* The background would probably be best done as a tiled image, gradients didn't seem to be reliable at this size of line.
* To make the red lines align, background-size needs to be adjusted from JS for every column so that the tiled image doesn't get cut in half at the edges of the column (because the column can have any width.)
* Another solution is to create a background element for every "block" of overbooked tasks and set tiled image as background. This way there wouldn't be problems with lines alignment.

**Comment by herkyl** [comment]
Another easy fix would be to either make the lines horizontal or vertical
